### ISSUE TITLE
Traceback #2 in console when setting a key

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/project#234]
# stratis key set --capture-key testkey
Might be related to https://github.com/stratis-storage/project/issues/233

OS: Fedora release 33 (Thirty Three) server
Version:
stratisd-2.1.0-3.fc33.x86_64
stratis-cli-2.1.1-2.fc33.noarch
This error was see using the BMC of a physical machine, where as, issue 233 was seen using the console from virt-manager
 
```
# stratis key set --capture-key testkey

stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below.
 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dbus_python_client_gen/_invokers.py", line 319, in dbus_func
    return dbus_method(*xformed_args, timeout=timeout)
  File "/user/lib64/python3.9/site-package/dbus/proxies.py", line 141, in _call_
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.9/site-packages/dbus/connections.py", line 652, in call_blocking
    reply_message = self.end_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Disconnected: Connections was disconnected before a reply was received

stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below. 

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 43, in the_func
    result.func(result)
  File "/usr/lib/python3.9/site-packages/stratis_cli/_parser/_parser.py", line 87, in wrapped_func
    func(*args)
  File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 679, in set_key
    ((changed, existing_modified), return_code, message) = _add_update_key(
  File "/usr/lib/python3.9/site-packages/stratis_cli/_actions/_top.py", line 210, in _add_update_key
    terminal_attributes = tcgetattr(file_desc)
termios.error: (25, 'Inappropriate ioctl for device')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/stratis", line 35, in <module>
    main()
  File "/usr/bin/stratis", line 32, in main
    return run()(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 65, in the_func
    handle_error(err)
  File "/usr/lib/python3.9/site-packages/stratis_cli/_error_reporting.py", line 289, in handle_error
    raise err
  File "/usr/lib/python3.9/site-packages/stratis_cli/_main.py", line 60, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['key', 'set', '--capture-key', 'testkey'] which were parsed to Namespace(propagate=False, func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7fa5ee07d8b0>, keydesc='testkey', keyfile_path=None, capture_key=True) failed
```

A workaround is to use the option --keyfile-path instead of --capture-key or use a terminal rather than the console.

**Comment by mulkieran** [comment]
Ok! We can close this in favor of #233.
