### ISSUE TITLE
Handle cross compilation in our -sys libraries

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/project#583]
It's a little bit unclear to me how to best approach this for all required uses cases in bindgen.

Sub issues:
* [libcryptsetup-rs](https://github.com/stratis-storage/libcryptsetup-rs/pull/278)
* [devicemapper-rs](https://github.com/stratis-storage/devicemapper-rs/issues/801)

**Comment by flxo** [comment]
Some notes on Android: 

I have a device mapper use case on android targets (`aarch64-linux-android`). The catchup with various crates that rely on bindgen stuff is major pain. Also for device mapper. My standard way of building for android is [cross](https://github.com/cross-rs/cross) that comes with a Docker container for android rust builds. The latest version doesn't include `libdevmapper.h`(none does) which makes totally sense because normally an application developer would never need to use it in applications (and isn't allowed to). Same story applies for e.g `binder`. 

```sh
   Compiling devicemapper-sys v0.1.5
error: failed to run custom build command for `devicemapper-sys v0.1.5`

Caused by:
  process didn't exit successfully: `/target/debug/build/devicemapper-sys-abb148ccab8c3f94/build-script-build` (exit status: 101)
  --- stderr
  dm.h:2:10: fatal error: 'libdevmapper.h' file not found
  thread 'main' panicked at 'Could not generate dm.h bindings: ClangDiagnostic("dm.h:2:10: fatal error: 'libdevmapper.h' file not found\n")', /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-sys-0.1.5/build.rs:24:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `devicemapper-sys v0.1.5`

Caused by:
  process didn't exit successfully: `/target/debug/build/devicemapper-sys-abb148ccab8c3f94/build-script-build` (exit status: 101)
  --- stderr
  dm.h:2:10: fatal error: 'libdevmapper.h' file not found
  thread 'main' panicked at 'Could not generate dm.h bindings: ClangDiagnostic("dm.h:2:10: fatal error: 'libdevmapper.h' file not found\n")', /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/devicemapper-sys-0.1.5/build.rs:24:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

A cross build that uses `bindgen` is always interesting because the toolchain headers need to exactly match the target ones. My guess is, that in a lot of cases this is not the case we're all just lucky that Linux API don't change that dramatically and things just work (TM). 

For checking this crate for android you would a NDK + [libdm](https://android.googlesource.com/platform/external/lvm2/+/refs/heads/master/libdm) which you don't get off the shelf (or revert https://github.com/stratis-storage/devicemapper-rs/commit/d66efa4c73ac8afd1e1bc2139f3159504baa028e#diff-fdb00b839f512eccbbdb64f45536cba6b07e26a3da7b432dbf37cf6ab5248aaf.
Building such a container is not straight forward - I don't have one and decided to fork the [android dm (verity)](https://cs.android.com/android/platform/superproject/+/master:packages/modules/Virtualization/libs/devicemapper/) parts.

**Comment by jbaublitz** [comment]
@flxo Would a solution like stratis-storage/libcryptsetup-rs#278 solve your problem too?

**Comment by flxo** [comment]
> @flxo Would a solution like [stratis-storage/libcryptsetup-rs#278](https://github.com/stratis-storage/libcryptsetup-rs/pull/278) solve your problem too?

Sorry for the late reply.

No - because `libdevmapper.h`doesn't exist in the cross sysroot in my case (`android`) there's no `-I`to add.

**Comment by jbaublitz** [comment]
We've had a number of issues come in like:
https://github.com/stratis-storage/libcryptsetup-rs/issues/223
https://github.com/stratis-storage/devicemapper-rs/issues/965
https://github.com/stratis-storage/libblkid-rs/pull/192

@flxo While this may no longer be helpful to you I'm returning to this issue.

In your case, I've reviewed everything that you've written and I believe it's a challenging use case for us to support. Given that the header file we use for generating data structures just isn't available, I feel like we could do one of two things: create a fallback data structure to use if the header is not present or else I think it would be best to try to build a container with the header available. I don't know the details of why this is difficult in your case so I'm willing to try to go with the first option if that is still interesting.

@posimind I believe that https://github.com/stratis-storage/devicemapper-rs/issues/965 is more of bandaid than a long term solution. I am probably going to revert that change and go with the solution that I've outlined in https://github.com/stratis-storage/libcryptsetup-rs/issues/223. This mainly involves namespacing all environment variables for pkg-config for each bindings library so that they are settable from the top level without having to mess with build.rs files for each individual library as is necessary now. I believe exposing the pkg-config cross-compile environment variables should still give you the opportunity to correctly configure the cross-compilation to your needs.

**Comment by flxo** [comment]
@jbaublitz Thanks for getting back to this. I agree that my issue can't be solved here and must be carefully handled by the integration. In essence my problem is the mismatch of the cross container with my production environment.
I no longer have any needs for getting this solved here and AFAIK (it's a long time ago) manually worked verified that the generated structures match my target kernel version.
