### ISSUE TITLE
TMT tests results in mkfs.xfs failure

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#664]
Note that tests are all being run on loopbacked device.

This test actually fails, but rather early in the test sequence, so it is probably not an error in the tests, but a real failure.

```
======================================================================
FAIL: test_filesystem_create_specified_size (__main__.StratisdCertify.test_filesystem_create_specified_size)
Test creating a filesystem with a specified size.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/ARTIFACTS/work-testing_HEADkg_f7klg/plans/testing_HEAD/discover/default-0/tests/testlib/utils.py", line 223, in modified_func
    return func(self)
           ^^^^^^^^^^
  File "/var/ARTIFACTS/work-testing_HEADkg_f7klg/plans/testing_HEAD/discover/default-0/tests/stratisd_cert.py", line 798, in test_filesystem_create_specified_size
    self._unittest_command(
  File "/var/ARTIFACTS/work-testing_HEADkg_f7klg/plans/testing_HEAD/discover/default-0/tests/stratisd_cert.py", line 184, in _unittest_command
    self.assertEqual(return_code, expected_return_code, msg=msg)
AssertionError: dbus.UInt16(1) != dbus.UInt16(0) : Command failed: cmd: "/usr/sbin/mkfs.xfs" "-f" "-q" "/dev/dm-5" "-m" "uuid=28ce93f7-69b7-4667-b695-695a25c1a3dd", exit reason: 1 stdout:  stderr: log stripe unit (1048576 bytes) is too large (maximum is 256KiB)
log stripe unit adjusted to 32KiB
mkfs.xfs: libxfs_device_zero write failed: Input/output error
```

**Comment by mulkieran** [comment]
We're pretty strongly convinced that the problem is due to the loopbacked devices not being able to be resized to hold the xfs metadata due to the restrictions on the filesystem that creates the backing storage. We still don't know why it's a problem on testing farm and not on Fedora containers, though.

**Comment by mulkieran** [comment]
Current logs from GitHub Actions:

```
INFO:root:temporary directory for loopbacked devices: /tmp/tmpjs93hzd__stratis_test_loopback
DEBUG:root:output of ['blockdev', '--getss', '/dev/loop3']: 512
DEBUG:root:output of ['blockdev', '--getpbsz', '/dev/loop3']: 512
DEBUG:root:output of ['blockdev', '--getiomin', '/dev/loop3']: 512
DEBUG:root:output of ['blockdev', '--getioopt', '/dev/loop3']: 0
DEBUG:root:output of ['blockdev', '--getss', '/dev/loop4']: 512
DEBUG:root:output of ['blockdev', '--getpbsz', '/dev/loop4']: 512
DEBUG:root:output of ['blockdev', '--getiomin', '/dev/loop4']: 512
DEBUG:root:output of ['blockdev', '--getioopt', '/dev/loop4']: 0
DEBUG:root:output of ['blockdev', '--getss', '/dev/loop5']: 512
DEBUG:root:output of ['blockdev', '--getpbsz', '/dev/loop5']: 512
DEBUG:root:output of ['blockdev', '--getiomin', '/dev/loop5']: 512
DEBUG:root:output of ['blockdev', '--getioopt', '/dev/loop5']: 0
```

and from TF:

```
INFO:root:temporary directory for loopbacked devices: /tmp/tmpy37ll7os_stratis_test_loopback
DEBUG:root:output of ['blockdev', '--getss', '/dev/loop0']: 512
DEBUG:root:output of ['blockdev', '--getpbsz', '/dev/loop0']: 512
DEBUG:root:output of ['blockdev', '--getiomin', '/dev/loop0']: 512
DEBUG:root:output of ['blockdev', '--getioopt', '/dev/loop0']: 0
DEBUG:root:output of ['blockdev', '--getss', '/dev/loop1']: 512
DEBUG:root:output of ['blockdev', '--getpbsz', '/dev/loop1']: 512
DEBUG:root:output of ['blockdev', '--getiomin', '/dev/loop1']: 512
DEBUG:root:output of ['blockdev', '--getioopt', '/dev/loop1']: 0
DEBUG:root:output of ['blockdev', '--getss', '/dev/loop2']: 512
DEBUG:root:output of ['blockdev', '--getpbsz', '/dev/loop2']: 512
DEBUG:root:output of ['blockdev', '--getiomin', '/dev/loop2']: 512
DEBUG:root:output of ['blockdev', '--getioopt', '/dev/loop2']: 0
```

not much difference to be seen.
