### ISSUE TITLE
File an issue against dbus-python monitor_dbus_signals.py not being informed PropertyChanged signals by callback 

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/project#741]
The evidence of the problem is here.

It appears to occur only when the script is run in the testing infrastructure.

The expected signals are always detected by ```dbus-monitor --system "path_namespace='/org/storage/stratis3'"``` run in a separate terminal.

```
======================================================================
FAIL: test_pool_add_data_init_cache (__main__.StratisdCertify)
Test adding data for a pool, then initializing the cache.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/runner/work/stratisd/stratisd/testing/stratisd_cert.py", line 193, in tearDown
self._post_test_checks.teardown()
File "/home/runner/work/stratisd/stratisd/testing/testlib/infra.py", line 636, in teardown
self.dbus_monitor.run_check(stop_time)
File "/home/runner/work/stratisd/stratisd/testing/testlib/infra.py", line 535, in run_check
self.assertEqual(
AssertionError: 1 != 0 : Error from monitor_dbus_signals:
DifferentProperty(dbus.ObjectPath('/org/storage/stratis3/77'), dbus.String('org.storage.stratis3.pool.r0'), dbus.String('AllocatedSize'), dbus.String('9196806144', variant_level=1), dbus.String('17179615232', variant_level=1))
DifferentProperty(dbus.ObjectPath('/org/storage/stratis3/77'), dbus.String('org.storage.stratis3.pool.r0'), dbus.String('TotalPhysicalUsed'), dbus.Struct((dbus.Boolean(True), dbus.String('2354847744')), signature=None, variant_level=1), dbus.Struct((dbus.Boolean(True), dbus.String('2356944896')), signature=None, variant_level=1))
DifferentProperty(dbus.ObjectPath('/org/storage/stratis3/77'), dbus.String('org.storage.stratis3.pool.r1'), dbus.String('AllocatedSize'), dbus.String('9196806144', variant_level=1), dbus.String('17179615232', variant_level=1))
```

**Comment by mulkieran** [comment]
We can get the same problem for running stratisd_cert.py directly, the PropertyChanged signal is not picked up by dbus-python main-loop but is picked up by dbus-monitor.
